build:
  binary: hcloud-kv
  main: main.go
  ldflags:
    - >
      -s -w
  goos:
    - linux
    - darwin
    - freebsd
    - windows
  goarch:
    - amd64
    - arm
    - arm64
  env:
    - CGO_ENABLED=0

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}_{{.Tag}}"

release:
  draft: true

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "checksums.txt"